---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Update package repos
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - include: tasks/packages.yml
    - include: tasks/docker.yml
      tags: [docker]
