---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Update package repos
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - import_tasks: tasks/neovim.yml
      when: configure_neovim
      tags: ['neovim']


    - include: tasks/packages.yml
      tags: ['packages']
    - include: tasks/docker.yml
      tags: [docker]
