---
- name: clone dotfiles repo
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_local }}"
    version: "{{ dotfiles_version}}"
    accept_hostkey: true
  become: false

- name: Create config directories
  file:
    state: directory
    dest: "{{ home }}/.config/{{ item }}"
  with_items:
    - "nvim"
    - "nvim/lua"
    - "git"

- name: Run install command for dotbot
  command:
    chdir: "{{ dotfiles_repo_local }}"
    cmd: "./install"
