---
# Get latest features by building NeoVim from source
- name: Checkout NeoVim source code
  git:
    repo: "{{ neovim_repo }}"
    version: nightly
    force: yes
    update: "{{ neovim_update }}"
    dest: "{{ home }}/Software/neovim"
    accept_hostkey: "{{ neovim_accept_hostkey }}"
  become: false

- name: Build NeoVim with make
  command:
    chdir: "{{ home }}/Software/neovim"
    cmd: "make --silent -j4"

- name: Install NeoVim
  command:
    chdir: "{{ home }}/Software/neovim"
    cmd: "make --silent install"
  become: yes

- name: Install vim-plug
  get_url:
    url: "{{ vimplug_url }}"
    dest: "{{ home }}/.local/share/nvim/site/autoload"

- name: Run PlugInstall non-interactively
  command:
    cmd: "nvim --headless -c PlugInstall -c qa"
