- name: Install apt packages
  apt:
    name:
      - htop
      - tmux

- name: Install flatpak packages
  community.general.flatpak:
    name: '{{ item }}'
  with_items:
    - com.slack.Slack
    - com.microsoft.Teams
      

