---
- name: Install apt packages
  become: yes
  apt:
    name: "{{ item}}"
  with_items: "{{ apt_packages }}"

- name: Install flatpak packages
  community.general.flatpak:
    name: '{{ item }}'
  with_items:
    - com.slack.Slack
    - com.microsoft.Teams
      

